version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_bet6
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  data: {}